### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rwsu** [open-cluster-management/multicloud-operators-subscription-release#39]
I deployed multicloud-operators-subscription-release using the image from quay.io/multicloudlab/multicloud-operators-subscription-release.

git clone https://github.com/IBM/multicloud-operators-subscription-release.git
cd multicloud-operators-subscription-release
kubectl apply -f deploy/crds
kubectl apply -f deploy

The multicloud-operators-subscription-release pod is in CrashLoopBackOff and the log shows: 

````
I0113 06:02:19.888918       1 main.go:57] Go Version: go1.13
I0113 06:02:19.889077       1 main.go:58] Go OS/Arch: linux/amd64
I0113 06:02:19.889169       1 main.go:59] Version of operator-sdk: v0.12.0
I0113 06:02:21.145589       1 main.go:117] Registering Components.
I0113 06:02:24.205082       1 main.go:160] Could not create ServiceMonitor object: no ServiceMonitor registered with the API
I0113 06:02:24.205131       1 main.go:164] Install prometheus-operator in your cluster to create ServiceMonitor objects: no ServiceMonitor registered with the API
I0113 06:02:24.205412       1 main.go:168] Starting the Cmd.
I0113 06:02:24.411800       1 helmchartsubscription_controller.go:127] Reconciling Subscription
E0113 06:02:24.412485       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 878 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x19a78c0, 0x2e9ea80)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:51 +0x82
panic(0x19a78c0, 0x2e9ea80)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/IBM/multicloud-operators-subscription-release/pkg/helmreposubscriber.(*HelmRepoSubscriber).doHelmChartSubscription(0xc000a2c0c0, 0x0, 0x2ee9f60)
	multicloud-operators-subscription-release/pkg/helmreposubscriber/hrsubscriber.go:145 +0x45
github.com/IBM/multicloud-operators-subscription-release/pkg/helmreposubscriber.(*HelmRepoSubscriber).Restart(0xc000a2c0c0, 0xc0006fbe90, 0xc0002e2000)
	multicloud-operators-subscription-release/pkg/helmreposubscriber/hrsubscriber.go:98 +0x315
github.com/IBM/multicloud-operators-subscription-release/pkg/controller/helmchartsubscription.(*ReconcileSubscription).Reconcile(0xc0006f7300, 0xc000a88699, 0x7, 0xc00097b080, 0x1d, 0xc0001e5cd8, 0xc000200000, 0xc0009e42d8, 0x1ec67c0)
	multicloud-operators-subscription-release/pkg/controller/helmchartsubscription/helmchartsubscription_controller.go:159 +0x8e6
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004972c0, 0x1a26140, 0xc000aac240, 0x0)
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:216 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004972c0, 0xf77500)
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:192 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0004972c0)
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:171 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0009dc090)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0009dc090, 0x3b9aca00, 0x0, 0xc0006d6c01, 0xc0004e56e0)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0009dc090, 0x3b9aca00, 0xc0004e56e0)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:157 +0x32e
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13efc25]
goroutine 878 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:58 +0x105
panic(0x19a78c0, 0x2e9ea80)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/IBM/multicloud-operators-subscription-release/pkg/helmreposubscriber.(*HelmRepoSubscriber).doHelmChartSubscription(0xc000a2c0c0, 0x0, 0x2ee9f60)
	multicloud-operators-subscription-release/pkg/helmreposubscriber/hrsubscriber.go:145 +0x45
github.com/IBM/multicloud-operators-subscription-release/pkg/helmreposubscriber.(*HelmRepoSubscriber).Restart(0xc000a2c0c0, 0xc0006fbe90, 0xc0002e2000)
	multicloud-operators-subscription-release/pkg/helmreposubscriber/hrsubscriber.go:98 +0x315
github.com/IBM/multicloud-operators-subscription-release/pkg/controller/helmchartsubscription.(*ReconcileSubscription).Reconcile(0xc0006f7300, 0xc000a88699, 0x7, 0xc00097b080, 0x1d, 0xc0001e5cd8, 0xc000200000, 0xc0009e42d8, 0x1ec67c0)
	multicloud-operators-subscription-release/pkg/controller/helmchartsubscription/helmchartsubscription_controller.go:159 +0x8e6
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004972c0, 0x1a26140, 0xc000aac240, 0x0)
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:216 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004972c0, 0xf77500)
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:192 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0004972c0)
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:171 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0009dc090)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0009dc090, 0x3b9aca00, 0x0, 0xc0006d6c01, 0xc0004e56e0)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0009dc090, 0x3b9aca00, 0xc0004e56e0)
	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:157 +0x32e
Logs from
to UTC
````

**Comment by mikeshng** [comment]
Issue should be fixed once we open the image to the public
https://github.com/open-cluster-management/multicloud-operators-subscription-release/blob/master/deploy/operator.yaml#L64

**Comment by pcuixa** [comment]
@mikeshng Is this still a valid issue?

**Comment by mikeshng** [comment]
@pcuixa The nil pointer has been fixed but the image is not open to public yet so its now getting this error

```

**Comment by mikeshng** [comment]
```
$ git clone git@github.com:open-cluster-management/multicloud-operators-subscription-release.git
$ cd multicloud-operators-subscription-release/
$ kubectl apply -f deploy/crds
$ kubectl apply -f deploy
$ kubectl get pod
NAME                                                           READY   STATUS    RESTARTS   AGE
multicluster-operators-subscription-release-6dccd47cdb-n5bdc   1/1     Running   0         
```

should be fix now.
